[package]
name = "glua"
version = "0.1.0"
authors = ["J0sh0nat0r <jojo.parillon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plex = { version = "0.2.5", featurs = ["lexer"] }
